version: "3"
   
services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s  
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      
    ports:
      - 5432:5432
  backend:
    build: .
    image: core-app:latest
    container_name: core-app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

