# Generated by Django 4.0.3 on 2022-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], max_length=100),
        ),
    ]
