# Generated by Django 4.0.3 on 2022-04-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], default='Viewer', max_length=100),
        ),
    ]
