# Generated by Django 4.0.3 on 2022-04-12 20:46

from django.db import migrations, models

def populate_roles(apps, schema_editor):
    names = ["Director", "Manager", "Viewer"]                               
    Role = apps.get_model('accounts', 'Role')
    for name in names:
        obj = Role(name=name)
        obj.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(populate_roles),  #Just add this line

    ]
